const fs = require('fs');

const data = `COMPLETE BLOOD COUNT (CBC)	350
HbA1c; GLYCOSYLATED HEMOGLOBIN	430
THYROID PROFILE TOTAL	540
URINE EXAMINATION, ROUTINE; URINE, R/E	120
GLUCOSE, FASTING (F) AND POST MEAL (PP), 2 HOURS	150
LIVER FUNCTION TEST (LFT)	790
KIDNEY FUNCTION TEST (KFT)	840
LIPID PROFILE BASIC	990
GLUCOSE, FASTING (F)	80
C-REACTIVE PROTEIN; CRP	430
LIVER & KIDNEY PANEL	1530
CULTURE URINE	840
HCG, BETA, TOTAL, QUANTITATIVE, MATERNAL	690
VITAMIN D 25 - HYDROXY	1530
VITAMIN B12; CYANOCOBALAMIN	1180
ESR; ERYTHROCYTE SEDIMENTATION RATE	140
CREATININE, SERUM	150
TSH (THYROID STIMULATING HORMONE)	200
URIC ACID, SERUM	160
HEMOGLOBIN; Hb	110
TSH (THYROID STIMULATING HORMONE), ULTRASENSITIVE	370
DENGUE FEVER NS1 ANTIGEN, EIA	750
GLUCOSE, POST PRANDIAL (PP), 2 HOURS	90
MALARIA PARASITE / BLOOD PARASITE IDENTIFICATION	130
IRON STUDIES	540
THYROID PROFILE, FREE	940
SGPT; ALANINE AMINOTRANSFERASE (ALT)	190
HIV 1 & 2 ANTIBODIES SCREENING TEST	520
SWASTH PLUS VITAMIN PANEL	1770
GLUCOSE, RANDOM (R)	80
BLOOD GROUP ABO & RH FACTOR	140
WIDAL SLIDE AGGLUTINATION TEST	290
FERRITIN	650
SWASTHFIT COMPLETE HEALTH CHECK- NEW	5020
PROLACTIN, SERUM	590
FEVER PANEL 1	640
CALCIUM, SERUM	190
CHOLESTEROL TOTAL	170
PLATELET COUNT	100
PROTHROMBIN TIME STUDIES	340
SODIUM, SERUM	190
HEMOGRAM	410
POTASSIUM, SERUM	190
ELECTROLYTES, SERUM	390
RHEUMATOID FACTOR (RA), SERUM	450
SWASTHFIT SUPER 2-NEW	2360
TESTOSTERONE, TOTAL	690
SGOT; ASPARTATE AMINOTRANSFERASE (AST)	190
URINE EXAMINATION, ROUTINE; URINE R/E, AUTOMATED	180
HEPATITIS B SURFACE ANTIGEN (HBSAG),QUALITATIVE	540
SWASTHFIT COMPLETE PACKAGE - NEW	5020
ANTI MULLERIAN HORMONE; AMH	2120
PSA (PROSTATE - SPECIFIC ANTIGEN), TOTAL	790
CORTISOL, SERUM (MORNING SAMPLE)	590
INSULIN, FASTING	790
HEPATITIS C ANTIBODY (Anti-HCV)	1580
FSH & LH	1080
MAGNESIUM, SERUM	540
Swasthfit Advance Health Checkup - Full Body Checkup	3940
CULTURE, URINE ADVANTAGE	890
ANTI THYROID PEROXIDASE ANTIBODY; ANTI TPO	1480
TYPHI DOT/ SALMONELLA TYPHI IGM	440
SARS-COV-2 (COVID-19) QUALITATIVE REAL TIME RE-PCR	490
STOOL EXAMINATION, ROUTINE; STOOL, R/E	130
IMMUNOGLOBULIN IgE, SERUM	890
MICROALBUMIN / ALBUMIN, 1ST MORNING / RANDOM URINE	590
HEMOGLOBIN HPLC/ELECTROPHORESIS	940
STD PANEL	2960
LIPID PROFILE EXTENDED	1480
FEVER PANEL - ADVANCE	1720
C-REACTIVE PROTEIN, CARDIO; hsCRP	790
TYPHIDOT/SALMONELLA TYPHI IGG & IGM	890
T4, FREE; FT4	360
ESTRADIOL (E2), SERUM	690
HOMOCYSTEINE QUANTITATIVE, SERUM	990
RPR, SERUM	190
WIDAL TUBE AGGLUTINATION TEST	340
CA 125; OVARIAN CANCER MARKER	1280
BLOOD PICTURE; PERIPHERAL BLOOD SMEAR EXAMINATION	160
ANTI CYCLIC CITRULLINATED PEPTIDE; ANTI CCP	1870
ANTI NUCLEAR ANTIBODY / FACTOR (ANA/ANF),EIA	790
UREA, SERUM	140
DIABETES PANEL BASIC	440
LIPASE	620
CA 19.9; PANCREATIC CANCER MARKER	1480
PTH (PARATHYROID HORMONE), INTACT	1580
ANTI NUCLEAR ANTIBODY / FACTOR (ANA / ANF),IFA(HEP-2)	2360
AMYLASE, SERUM	490
PROGESTERONE, SERUM	590
PROTEIN - CREATININE RATIO, URINE	490
BILE ACID TOTAL, SERUM	1480
CEA; CARCINO EMBRYONIC ANTIGEN	730
SWASTHFIT SUPER 4-NEW	4040
TESTOSTERONE PANEL, TOTAL & FREE	2560
HOMA-IR ; INSULIN RESISTANCE INDEX	910
STOOL EXAMINATION, OCCULT BLOOD	160
CK; CREATINE KINASE	1970
HELICOBACTER PYLORI ANTIGEN, RAPID STOOL TEST	1580
MALARIA VIVAX AND FALCIPARUM ANTIGEN	690`;

const lines = data.trim().split('\n');
const tests = [];
let id = 1000;
const pseudoRandom = (seed) => {
  const x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
};

lines.forEach((line, index) => {
  const parts = line.split('\t');
  if (parts.length === 2) {
    const name = parts[0].trim();
    const price = parseInt(parts[1].trim());
    if (name && !isNaN(price)) {
      const isPackage = name.toLowerCase().includes('swasth') || name.toLowerCase().includes('panel') || name.toLowerCase().includes('package') || name.toLowerCase().includes('checkup');
      
      tests.push({
        id: 'LAL-' + id++,
        name: name,
        category: isPackage ? 'Health Package' : 'Individual Test',
        price: price,
        discountPrice: price,
        turnaroundTime: pseudoRandom(index) > 0.5 ? '12 Hours' : '24 Hours',
        fastingRequired: name.includes('FASTING') || isPackage || pseudoRandom(index * 5) > 0.8,
        homeCollection: true,
        includedTests: isPackage ? ['COMPLETE BLOOD COUNT (CBC)', 'LIPID PROFILE BASIC'] : undefined
      });
    }
  }
});
fs.writeFileSync('drLalTests.json', JSON.stringify(tests, null, 2));
console.log('Generated drLalTests.json');
